import type { CSSObject, Theme } from '@emotion/react';

export const workspaceStyles = (theme: Theme, embedded: boolean): CSSObject => ({
  width: embedded ? '100%' : `calc(100% + (${theme.space.md} * 2))`,
  minWidth: 0,
  minHeight: embedded ? 'min(34rem, 70dvh)' : 0,
  height: embedded ? 'auto' : `calc(100% + (${theme.space.md} * 2))`,
  margin: embedded ? 0 : `calc(-1 * ${theme.space.md})`,
  display: 'grid',
  containerType: 'inline-size',
  gridTemplateRows: embedded ? 'auto auto auto' : 'minmax(0, 1fr) auto',
  overflow: embedded ? 'visible' : 'hidden',
  color: theme.colors.text,
  background: theme.colors.canvas,
  '& h3, & h4, & h5, & p': { margin: 0 },
});

export const workspaceHeaderStyles = (theme: Theme): CSSObject => ({
  display: 'flex',
  alignItems: 'start',
  justifyContent: 'space-between',
  gap: theme.space.md,
  padding: theme.space.md,
  borderBlockEnd: `1px solid ${theme.colors.border}`,
  '& > div': { minWidth: 0 },
  '& h3': { fontFamily: theme.type.display, fontSize: theme.fontSizes.section },
  '& p': {
    marginBlockStart: theme.space.xxs,
    color: theme.colors.textMuted,
    fontSize: theme.fontSizes.body,
    lineHeight: 1.45,
  },
  '& > span': {
    flex: '0 0 auto',
    padding: `0.2rem ${theme.space.xs}`,
    borderRadius: theme.radii.round,
    color: theme.colors.accentStrong,
    background: theme.colors.accentSoft,
    fontSize: theme.fontSizes.caption,
    fontWeight: 760,
  },
});

export const workspaceBodyStyles = (theme: Theme, embedded: boolean): CSSObject => ({
  minWidth: 0,
  minHeight: 0,
  display: 'grid',
  gridTemplateColumns: '20rem minmax(0, 1fr)',
  overflow: embedded ? 'visible' : 'hidden',
  '@media (max-width: 48rem)': {
    gridTemplateColumns: 'minmax(0, 1fr)',
    gridTemplateRows: 'auto minmax(0, 1fr)',
    overflow: embedded ? 'visible' : 'hidden',
  },
  '@container (max-width: 48rem)': {
    gridTemplateColumns: 'minmax(0, 1fr)',
    gridTemplateRows: 'auto minmax(0, 1fr)',
    overflow: embedded ? 'visible' : 'hidden',
  },
});

export const treatmentRailStyles = (theme: Theme): CSSObject => ({
  minWidth: 0,
  minHeight: 0,
  display: 'grid',
  gridTemplateRows: 'auto minmax(0, 1fr) auto',
  alignContent: 'start',
  gap: theme.space.md,
  padding: theme.space.lg,
  borderInlineEnd: `1px solid ${theme.colors.border}`,
  background: `color-mix(in srgb, ${theme.colors.canvasRaised} 70%, transparent)`,
  '& > h3': { fontSize: theme.fontSizes.body, fontWeight: 700 },
  '@media (max-width: 48rem)': {
    gridTemplateRows: 'auto auto',
    gap: theme.space.sm,
    padding: theme.space.md,
    borderInlineEnd: 0,
    borderBlockEnd: `1px solid ${theme.colors.border}`,
    '& details': { display: 'none' },
  },
  '@container (max-width: 48rem)': {
    gridTemplateRows: 'auto auto',
    gap: theme.space.sm,
    padding: theme.space.md,
    borderInlineEnd: 0,
    borderBlockEnd: `1px solid ${theme.colors.border}`,
    '& details': { display: 'none' },
  },
  '@media (max-width: 40rem)': { paddingInline: theme.space.sm },
});

export const treatmentListStyles = (theme: Theme): CSSObject => ({
  minWidth: 0,
  minHeight: 0,
  display: 'grid',
  alignContent: 'start',
  gap: theme.space.xs,
  margin: 0,
  padding: `0 ${theme.space.xxs} 0 0`,
  listStyle: 'none',
  overflowY: 'auto',
  overscrollBehaviorBlock: 'contain',
  scrollbarWidth: 'thin',
  '@media (max-width: 48rem)': {
    gridAutoFlow: 'column',
    gridAutoColumns: 'minmax(12rem, 15rem)',
    gridTemplateColumns: 'none',
    overflowX: 'auto',
    overflowY: 'hidden',
    overscrollBehaviorInline: 'contain',
    scrollbarWidth: 'thin',
    paddingBlockEnd: theme.space.xxs,
  },
  '@container (max-width: 48rem)': {
    gridAutoFlow: 'column',
    gridAutoColumns: 'minmax(12rem, 15rem)',
    gridTemplateColumns: 'none',
    overflowX: 'auto',
    overflowY: 'hidden',
    overscrollBehaviorInline: 'contain',
    scrollbarWidth: 'thin',
    paddingBlockEnd: theme.space.xxs,
  },
});

export const treatmentChoiceStyles = (theme: Theme, selected: boolean): CSSObject => ({
  width: '100%',
  minHeight: '4.25rem',
  display: 'grid',
  gridTemplateColumns: '2.5rem minmax(0, 1fr)',
  alignItems: 'center',
  gap: theme.space.sm,
  padding: theme.space.sm,
  border: `1px solid ${selected ? theme.colors.accent : theme.colors.border}`,
  borderRadius: theme.radii.medium,
  color: selected ? theme.colors.accent : theme.colors.text,
  background: selected ? theme.colors.accentSoft : theme.colors.surface,
  boxShadow: selected ? '0 0 12px rgba(98, 230, 194, 0.1)' : 'none',
  textAlign: 'start',
  cursor: 'pointer',
  transition: `border-color ${theme.motion.quick}, background ${theme.motion.quick}`,
  '&:hover:not(:disabled)': { borderColor: theme.colors.borderStrong },
  '&:focus-visible': { outline: `2px solid ${theme.colors.focus}`, outlineOffset: '3px' },
  '&:disabled': { cursor: 'not-allowed', opacity: 0.48 },
  '& [data-choice-mark]': {
    width: '2.5rem',
    height: '2.5rem',
    display: 'grid',
    placeItems: 'center',
    borderRadius: theme.radii.round,
    color: selected ? theme.colors.onAccent : theme.colors.textMuted,
    background: selected ? theme.colors.accent : theme.colors.surfaceStrong,
    fontSize: theme.fontSizes.label,
    fontWeight: 800,
  },
  '& strong, & small': {
    display: 'block',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  '& strong': { fontSize: theme.fontSizes.body },
  '& small': {
    marginBlockStart: theme.space.xxs,
    color: selected ? theme.colors.accentStrong : theme.colors.textMuted,
    fontSize: theme.fontSizes.caption,
    lineHeight: 1.3,
  },
});

export const compatibilityStyles = (theme: Theme): CSSObject => ({
  paddingBlockStart: theme.space.md,
  borderBlockStart: `1px solid ${theme.colors.border}`,
  color: theme.colors.textMuted,
  fontSize: theme.fontSizes.metadata,
  '& summary': {
    minHeight: '2.75rem',
    display: 'flex',
    alignItems: 'center',
    color: theme.colors.textMuted,
    cursor: 'pointer',
    fontWeight: 720,
  },
  '& p': {
    padding: theme.space.sm,
    borderRadius: theme.radii.small,
    background: theme.colors.surfaceStrong,
    lineHeight: 1.5,
  },
});

export const workspaceContentStyles = (theme: Theme, embedded: boolean): CSSObject => ({
  minWidth: 0,
  minHeight: 0,
  padding: theme.space.lg,
  overflow: embedded ? 'visible' : 'auto',
  overscrollBehavior: 'contain',
  scrollbarGutter: embedded ? undefined : 'stable',
  background: theme.colors.canvas,
  '@media (max-width: 48rem)': { padding: theme.space.md },
  '@container (max-width: 48rem)': { padding: theme.space.md },
  '@media (max-width: 40rem)': {
    padding: theme.space.sm,
    scrollbarGutter: 'auto',
  },
});

export const selectionPanelStyles = (theme: Theme): CSSObject => ({
  minWidth: 0,
  display: 'grid',
  alignContent: 'start',
  gap: theme.space.md,
});

export const selectionHeadingStyles = (theme: Theme): CSSObject => ({
  display: 'flex',
  alignItems: 'start',
  justifyContent: 'space-between',
  gap: theme.space.sm,
  paddingBlockEnd: theme.space.md,
  borderBlockEnd: `1px solid ${theme.colors.border}`,
  '& > div': { minWidth: 0 },
  '& h4': { fontFamily: theme.type.display, fontSize: theme.fontSizes.section },
  '& p': { marginBlockStart: theme.space.xs, color: theme.colors.textMuted, lineHeight: 1.5 },
  '& > span': {
    flex: '0 0 auto',
    padding: `0.2rem ${theme.space.xs}`,
    borderRadius: theme.radii.small,
    color: theme.colors.accent,
    background: theme.colors.accentSoft,
    fontSize: '0.65rem',
    fontWeight: 800,
    letterSpacing: '0.05em',
    textTransform: 'uppercase',
  },
});

export const sourceSummaryStyles = (theme: Theme): CSSObject => ({
  minHeight: '8rem',
  display: 'grid',
  gridTemplateColumns: '3rem minmax(0, 1fr)',
  alignItems: 'center',
  gap: theme.space.md,
  padding: theme.space.md,
  border: `1px solid ${theme.colors.border}`,
  borderRadius: theme.radii.medium,
  background: theme.colors.surface,
  '& [data-source-mark]': {
    width: '3rem',
    height: '3rem',
    display: 'grid',
    placeItems: 'center',
    borderRadius: theme.radii.round,
    color: theme.colors.accent,
    background: theme.colors.surfaceStrong,
    fontSize: '1.35rem',
  },
  '& strong': { display: 'block' },
  '& p': { marginBlockStart: theme.space.xs, color: theme.colors.textMuted, lineHeight: 1.5 },
  '& small': { display: 'block', marginBlockStart: theme.space.sm, color: theme.colors.textFaint },
});

export const statusStackStyles = (theme: Theme): CSSObject => ({
  display: 'grid',
  gap: theme.space.xs,
});

export const workspaceFooterStyles = (theme: Theme, embedded: boolean): CSSObject => ({
  minWidth: 0,
  display: 'grid',
  gridTemplateColumns: 'minmax(13rem, 1fr) auto',
  alignItems: 'center',
  gap: theme.space.lg,
  padding: embedded ? theme.space.md : `${theme.space.md} ${theme.space.lg}`,
  borderBlockStart: `1px solid ${theme.colors.border}`,
  background: theme.colors.canvasRaised,
  boxShadow: '0 -12px 40px rgba(0, 0, 0, 0.5)',
  '& [data-footer-selection]': {
    minWidth: 0,
    display: 'grid',
    gridTemplateColumns: '3rem minmax(0, 1fr)',
    alignItems: 'center',
    gap: theme.space.md,
  },
  '& [data-footer-mark]': {
    width: '3rem',
    height: '3rem',
    display: 'grid',
    placeItems: 'center',
    border: `1px solid ${theme.colors.borderStrong}`,
    borderRadius: theme.radii.medium,
    color: theme.colors.accent,
    background: theme.colors.surfaceStrong,
    fontSize: '1.35rem',
  },
  '& [data-footer-kicker]': {
    color: theme.colors.textMuted,
    fontSize: theme.fontSizes.caption,
    fontWeight: 800,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
  },
  '& [data-footer-name]': {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: theme.fontSizes.label,
    fontWeight: 700,
  },
  '& [data-footer-name] span': { color: theme.colors.textFaint, fontWeight: 400 },
  '& [data-footer-actions]': {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'end',
    gap: theme.space.md,
  },
  '& [data-footer-disclosure]': {
    maxWidth: '22rem',
    color: theme.colors.textMuted,
    fontSize: theme.fontSizes.caption,
    lineHeight: 1.45,
    textAlign: 'end',
  },
  '& [data-footer-disclosure] strong': { display: 'block', color: theme.colors.warning },
  '& [data-footer-primary]': {
    minHeight: '3rem',
    paddingInline: theme.space.xl,
    borderColor: 'transparent',
    color: theme.colors.onAccent,
    background: `linear-gradient(145deg, ${theme.colors.accentStrong}, ${theme.colors.accent})`,
    boxShadow: '0 4px 20px rgba(98, 230, 194, 0.3)',
  },
  '@media (max-width: 56rem)': {
    gridTemplateColumns: 'minmax(0, 1fr)',
    gap: theme.space.sm,
    '& [data-footer-actions]': { justifyContent: 'stretch' },
    '& [data-footer-disclosure]': { flex: '1 1 auto', textAlign: 'start' },
  },
  '@container (max-width: 56rem)': {
    gridTemplateColumns: 'minmax(0, 1fr)',
    gap: theme.space.sm,
    '& [data-footer-actions]': { justifyContent: 'stretch' },
    '& [data-footer-disclosure]': { flex: '1 1 auto', textAlign: 'start' },
  },
  '@media (max-width: 40rem)': {
    padding: `${theme.space.sm} max(${theme.space.sm}, env(safe-area-inset-right)) max(${theme.space.sm}, env(safe-area-inset-bottom)) max(${theme.space.sm}, env(safe-area-inset-left))`,
    '& [data-footer-selection]': {
      gridTemplateColumns: '2.5rem minmax(0, 1fr)',
      gap: theme.space.sm,
    },
    '& [data-footer-mark]': { width: '2.5rem', height: '2.5rem' },
    '& [data-footer-actions]': { display: 'grid', gridTemplateColumns: 'minmax(0, 1fr)' },
    '& [data-footer-disclosure]': { display: 'none' },
    '& [data-footer-primary]': { width: '100%', paddingInline: theme.space.md },
  },
});
