import type { CSSObject, Theme } from '@emotion/react';
import { media } from '../../ui/media';

export const workspaceMastheadStyles = (theme: Theme): CSSObject => ({
  gridColumn: '1 / -1',
  gridRow: 1,
  minWidth: 0,
  height: '3rem',
  display: 'flex',
  alignItems: 'center',
  gap: theme.space.md,
  paddingInline: theme.space.md,
  borderBlockEnd: `1px solid ${theme.colors.borderStrong}`,
  background: theme.colors.canvas,
  '& [data-detail-breadcrumb]': {
    minWidth: 0,
    minHeight: '2rem',
    flex: '0 0 auto',
    gap: theme.space.xxs,
    padding: 0,
    border: 0,
    borderRadius: 0,
    color: theme.colors.textMuted,
    background: 'transparent',
    boxShadow: 'none',
    fontSize: '0.6875rem',
    fontWeight: 650,
    whiteSpace: 'nowrap',
    '&:hover:not(:disabled):not([aria-disabled="true"])': {
      color: theme.colors.text,
      background: 'transparent',
      transform: 'none',
    },
  },
  '& [data-detail-breadcrumb] svg': { width: '0.9rem', height: '0.9rem' },
  '& [data-workspace-divider]': {
    width: '1px',
    height: '1rem',
    flex: '0 0 auto',
    background: theme.colors.border,
  },
  '& [data-workspace-title]': {
    minWidth: 0,
    display: 'flex',
    flex: '1 1 auto',
    alignItems: 'center',
    gap: theme.space.sm,
  },
  '& h1': {
    minWidth: 0,
    margin: 0,
    overflow: 'hidden',
    color: theme.colors.text,
    fontFamily: theme.type.sans,
    fontSize: theme.fontSizes.body,
    fontWeight: 680,
    letterSpacing: '-0.015em',
    lineHeight: 1.2,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  '& [data-workspace-project-status]': {
    minHeight: '1.2rem',
    display: 'inline-flex',
    alignItems: 'center',
    paddingInline: theme.space.xs,
    borderRadius: theme.radii.round,
    color: theme.colors.accent,
    background: theme.colors.accentSoft,
    fontSize: '0.5rem',
    fontWeight: 800,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  '& [data-workspace-save-status]': {
    minWidth: 0,
    display: 'inline-flex',
    flex: '0 0 auto',
    alignItems: 'center',
    gap: theme.space.xs,
    color: theme.colors.accent,
    fontSize: '0.6875rem',
    fontWeight: 650,
    whiteSpace: 'nowrap',
  },
  '& [data-workspace-save-status][data-tone="warning"]': { color: theme.colors.warning },
  '& [data-workspace-save-status][data-tone="danger"]': { color: theme.colors.danger },
  '& [data-workspace-save-status-dot]': {
    width: '0.4rem',
    height: '0.4rem',
    flex: '0 0 auto',
    borderRadius: '50%',
    background: 'currentColor',
  },
  '@media (max-width: 31.99rem)': {
    gap: theme.space.sm,
    paddingInline: theme.space.sm,
    '& [data-workspace-divider], & [data-workspace-project-status]': { display: 'none' },
    '& h1': { fontSize: theme.fontSizes.metadata },
    '& [data-workspace-save-status]': { fontSize: '0.625rem' },
  },
  '@media (max-width: 22rem)': {
    '& [data-workspace-save-label]': { display: 'none' },
  },
});

export const taskInspectorStyles = (theme: Theme): CSSObject => ({
  gridColumn: 2,
  gridRow: 2,
  minWidth: 0,
  minHeight: 0,
  display: 'flex',
  flexDirection: 'column',
  overflow: 'hidden',
  borderInlineStart: `1px solid ${theme.colors.border}`,
  background: theme.colors.canvas,
  [media.down('laptop')]: {
    gridColumn: 1,
    gridRow: 3,
    minHeight: '34rem',
    overflow: 'visible',
    borderInlineStart: 0,
    borderBlockStart: `1px solid ${theme.colors.border}`,
  },
});

export const taskNavigationStyles = (theme: Theme): CSSObject => ({
  position: 'sticky',
  zIndex: 2,
  insetBlockStart: 0,
  minHeight: '4.4rem',
  display: 'grid',
  gridTemplateColumns: 'repeat(4, minmax(0, 1fr))',
  gap: theme.space.xxs,
  padding: theme.space.xs,
  borderBlockEnd: `1px solid ${theme.colors.border}`,
  background: theme.colors.canvas,
  '& > button': {
    position: 'relative',
    minWidth: 0,
    minHeight: '3.5rem',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: theme.space.xxs,
    padding: `${theme.space.xs} ${theme.space.xxs}`,
    border: 0,
    borderRadius: theme.radii.medium,
    color: theme.colors.textMuted,
    background: 'transparent',
    fontFamily: 'inherit',
    cursor: 'pointer',
  },
  '& > button:hover': { color: theme.colors.text, background: theme.colors.surfaceSoft },
  '& > button[aria-selected="true"]': {
    color: theme.colors.text,
    background: theme.colors.surfaceStrong,
  },
  '& > button[aria-selected="true"]::after': {
    position: 'absolute',
    insetBlockEnd: 0,
    insetInlineStart: '50%',
    width: '1.5rem',
    height: '2px',
    background: theme.colors.accent,
    content: '""',
    transform: 'translateX(-50%)',
  },
  '& > button:focus-visible': {
    outline: `2px solid ${theme.colors.focus}`,
    outlineOffset: '-2px',
  },
  '& svg': { width: '1.1rem', height: '1.1rem' },
  '& span': {
    overflow: 'hidden',
    fontSize: '0.5625rem',
    fontWeight: 800,
    letterSpacing: '0.12em',
    textOverflow: 'ellipsis',
    textTransform: 'uppercase',
  },
});

export const taskBodyStyles = (theme: Theme): CSSObject => ({
  minWidth: 0,
  minHeight: 0,
  flex: '1 1 auto',
  overflowY: 'auto',
  overscrollBehavior: 'contain',
  scrollbarGutter: 'stable',
  '&::-webkit-scrollbar': { width: '8px' },
  '&::-webkit-scrollbar-thumb': {
    borderRadius: theme.radii.round,
    background: theme.colors.border,
  },
  [media.down('laptop')]: { overflow: 'visible' },
});

export const taskPanelStyles = (theme: Theme): CSSObject => ({
  minWidth: 0,
  display: 'grid',
  alignContent: 'start',
  gap: theme.space.lg,
  padding: `${theme.space.lg} clamp(${theme.space.lg}, 2vw, ${theme.space.xl}) 6rem`,
  '&[hidden]': { display: 'none' },
  '& > header': { display: 'grid', gap: theme.space.xxs },
  '& > header h2': {
    margin: 0,
    fontFamily: theme.type.display,
    fontSize: '1.125rem',
    fontWeight: 650,
    letterSpacing: '-0.015em',
  },
  '& > header p': {
    margin: 0,
    color: theme.colors.textMuted,
    fontSize: theme.fontSizes.metadata,
    lineHeight: 1.45,
  },
  '& > section, & > [role="status"], & > [role="alert"]': {
    boxShadow: 'none',
  },
  [media.down('tablet')]: {
    padding: `${theme.space.lg} ${theme.space.md} 5.5rem`,
  },
});
