import type { CSSObject, Theme } from '@emotion/react';

export const projectOverviewInnerStyles = (theme: Theme): CSSObject => ({
  width: 'min(100%, 88rem)',
  minHeight: '100%',
  marginInline: 'auto',
  display: 'grid',
  gridTemplateColumns: 'minmax(0, 1fr)',
  alignContent: 'start',
  '& > [role="status"]:empty': { display: 'none' },
  '@container (max-width: 52rem)': {
    paddingInline: 'clamp(1.5rem, 4cqi, 2.5rem)',
  },
  '@container (max-width: 30rem)': {
    paddingBlock: theme.space.xl,
    paddingInline: theme.space.md,
  },
});

export const projectOverviewHeaderStyles = (theme: Theme): CSSObject => ({
  minWidth: 0,
  display: 'grid',
  gridTemplateColumns: 'minmax(0, 1fr)',
  '& [data-detail-breadcrumb]': {
    justifySelf: 'start',
    minWidth: 0,
    minHeight: '2.75rem',
    marginBlockEnd: theme.space.xl,
    padding: `${theme.space.xs} 0`,
    border: 0,
    borderRadius: 0,
    color: theme.colors.textMuted,
    background: 'transparent',
    boxShadow: 'none',
    fontSize: theme.fontSizes.body,
    fontWeight: 600,
    '&:hover:not(:disabled):not([aria-disabled="true"])': {
      color: theme.colors.text,
      background: 'transparent',
      transform: 'none',
    },
  },
  '& [data-detail-identity]': {
    minWidth: 0,
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    alignItems: 'end',
    gap: theme.space.xl,
    paddingBlockEnd: '2.5rem',
    borderBlockEnd: `1px solid ${theme.colors.border}`,
  },
  '& [data-detail-identity] > div:first-of-type': {
    minWidth: 0,
    width: '100%',
  },
  '& h1': {
    width: '100%',
    maxWidth: '48rem',
    margin: 0,
    overflowWrap: 'anywhere',
    fontFamily: theme.type.display,
    fontSize: 'clamp(2.25rem, 4cqi, 3rem)',
    fontWeight: 660,
    letterSpacing: '-0.05em',
    lineHeight: 1,
  },
  '& [data-detail-meta]': {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    columnGap: theme.space.lg,
    rowGap: theme.space.xs,
    marginBlockStart: theme.space.md,
    color: theme.colors.textMuted,
    fontSize: theme.fontSizes.body,
  },
  '& [data-project-overview-status]': {
    color: theme.colors.accent,
    fontSize: '0.6875rem',
    fontWeight: 760,
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
  },
  '& [data-project-workspace-status]': {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: theme.space.xs,
    marginBlockStart: theme.space.lg,
    color: theme.colors.textFaint,
    fontSize: theme.fontSizes.metadata,
    lineHeight: 1.5,
  },
  '& [data-project-workspace-status] svg': {
    width: '1rem',
    height: '1rem',
    flex: '0 0 auto',
    color: theme.colors.accent,
  },
  '& [data-detail-actions]': {
    minWidth: 0,
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: `${theme.space.xs} ${theme.space.lg}`,
  },
  '& [data-detail-actions] > button': {
    minWidth: 0,
    minHeight: '2.75rem',
    padding: `${theme.space.xs} 0`,
    border: 0,
    borderRadius: 0,
    color: theme.colors.textMuted,
    background: 'transparent',
    boxShadow: 'none',
    fontSize: theme.fontSizes.body,
    fontWeight: 600,
    '&:hover:not(:disabled):not([aria-disabled="true"])': {
      color: theme.colors.text,
      background: 'transparent',
      transform: 'none',
    },
  },
  '& [data-detail-actions] > button[data-detail-action="continue"]': {
    minWidth: '9.5rem',
    paddingInline: theme.space.lg,
    borderRadius: theme.radii.small,
    color: theme.colors.onAccent,
    background: theme.colors.accent,
    '&:hover:not(:disabled):not([aria-disabled="true"])': {
      color: theme.colors.onAccent,
      background: theme.colors.accentStrong,
    },
  },
  '@container (max-width: 64rem)': {
    '& [data-detail-identity]': {
      gridTemplateColumns: 'minmax(0, 1fr)',
      alignItems: 'stretch',
    },
    '& [data-detail-identity] > div:first-of-type': { maxWidth: 'none' },
    '& h1': { maxWidth: 'none' },
    '& [data-detail-actions]': { justifyContent: 'flex-start' },
  },
  '@container (max-width: 30rem)': {
    '& [data-detail-breadcrumb]': { marginBlockEnd: theme.space.lg },
    '& [data-detail-identity]': { gap: theme.space.lg, paddingBlockEnd: theme.space.xl },
    '& h1': { fontSize: 'clamp(2rem, 11cqi, 2.6rem)' },
    '& [data-detail-meta]': { columnGap: theme.space.md, fontSize: theme.fontSizes.metadata },
    // One primary and one overflow: the primary takes the width it needs, the menu stays square.
    '& [data-detail-actions]': {
      display: 'grid',
      gridTemplateColumns: 'minmax(0, 1fr) auto',
      justifyContent: 'stretch',
      columnGap: theme.space.sm,
    },
    '& [data-detail-actions] > button[data-detail-action="continue"]': { width: '100%' },
  },
});

export const projectOverviewSourceStyles = (theme: Theme): CSSObject => ({
  minWidth: 0,
  display: 'grid',
  gridTemplateColumns: 'minmax(0, 1fr)',
  alignContent: 'start',
  gap: theme.space.md,
  paddingBlock: `clamp(${theme.space.xl}, 4cqi, 2.5rem) 0`,
  '& > header': { minWidth: 0, display: 'grid', gap: theme.space.xs },
  '& > header h2': {
    margin: 0,
    fontFamily: theme.type.display,
    fontSize: '1.25rem',
  },
  '& > header p': {
    margin: 0,
    color: theme.colors.textMuted,
    fontSize: theme.fontSizes.metadata,
    lineHeight: 1.55,
  },
});
